version: '3'
services:
  app:
    image: archivesspace/archivesspace:3.2.0
    container_name: archivesspace
    restart: on-failure
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8089:8089"
      - "8090:8090"
    depends_on:
      - db
      - solr
    environment:
      APPCONFIG_FRONTEND_PROXY_URL: 'http://localhost:8080'
      APPCONFIG_PUBLIC_PROXY_URL: 'http://localhost:8081'
      APPCONFIG_SOLR_URL: 'http://solr:8983/solr/archivesspace'
      ASPACE_DEPLOY_PKG_URL: 'https://s3-us-west-2.amazonaws.com/aspace-artifacts/puifalsc/deploy/puifalsc.zip'
      ASPACE_JAVA_XMX: "-Xmx2048m"
      DB_ADDR: db
      DB_NAME: archivesspace
      DB_USER: as
      DB_PASS: as123
      JAVA_OPTS: "-Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xss1024k -Djavax.accessibility.assistive_technologies=''"
      NEWRELIC_APP_NAME: artifacts
      NEWRELIC_KEY: artifacts
  db:
    image: mysql:8
    cap_add:
      - SYS_NICE
    container_name: mysql
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2 --log_bin_trust_function_creators=1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: archivesspace
      MYSQL_USER: as
      MYSQL_PASSWORD: as123
  solr:
    image: archivesspace/solr:3.2.0
    container_name: solr
    command: solr-create -p 8983 -c archivesspace -d archivesspace
    ports:
      - "8983:8983"
